language: python
branches:
  only:
    - wpt-downstream
python:
  - "2.7"
# command to install dependencies
install: "cd wpt-sync; pip install -r requirements.txt"
# command to run tests
script: pytest wpt-sync/test
